
version: 2

models:

  - name: fct_sessions
    description: "Session level summary with total submitted orders & gmv, AOV, promo usage, first & last order information"
    columns:
      - name: session_guid
        description: "session GUID"
        tests:
          - not_null
          - unique
      


